/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-16 16:27:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pagina.formularios;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formulario_002dinv_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Formulario de Inventario</title>\n");
      out.write("    <link href=\"../estilos/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../estilos/styles.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"fondo-imagen\">\n");
      out.write("\n");
      out.write("    <header class=\"container bg-dark col-6 rounded\">\n");
      out.write("        <h1 class=\"text-primary text-center\">\n");
      out.write("            Editar Formulario\n");
      out.write("        </h1>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <nav>\n");
      out.write("        <div id=\"barra-nav\" class=\"bg-dark\">\n");
      out.write("            <ul class=\"nav justify-content-center\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"../index.html\"> Inicio </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"../recetas.html\"> Recetas </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"../inventario.html\">Inventario</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"../menu.html\">Menú</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"container col-md-6 bg-dark mt-3\">\n");
      out.write("        <h1 class=\"text-primary\">Formulario de Inventario</h1>\n");
      out.write("        <form class=\"form\" method=\"post\" action=\"../../ValidacionFormulario\"> OJO AQUI\n");
      out.write("            <div class=\"form-group mt-1\">\n");
      out.write("                <label for=\"nombreIngrediente\" class=\"text-primary\">Nombre del Ingrediente</label>\n");
      out.write("                <input type=\"text\" name=\"ingrediente\" class=\"form-control\" id=\"nombreIngrediente\" placeholder=\"Ejemplo: Lechuga\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"tipoProducto\" class=\"text-primary\">Tipo de Producto</label>\n");
      out.write("                <select class=\"form-control\" id=\"tipoProducto\" name=\"tipoProducto\" >\n");
      out.write("                    <option value=\"Seleccionar\">Seleccionar</option>\n");
      out.write("                    <option value=\"Producto Perecedero\">Producto Perecedero</option>\n");
      out.write("                    <option value=\"Producto para Empacar\">Producto para Empacar</option>\n");
      out.write("                    <option value=\"Otros\">Otros</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"cantidadExistencia\" class=\"text-primary\">Cantidad</label>\n");
      out.write("                <input type=\"number\" class=\"form-control\" id=\"cantidadExistencia\" placeholder=\"Ejemplo: 100\" name=\"cantidadExistencia\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"medida\" class=\"text-primary\">Medida</label>\n");
      out.write("                <select class=\"form-control\" id=\"medida\" name=\"medida\">\n");
      out.write("                    <option value=\"Seleccionar\">Seleccionar</option>\n");
      out.write("                    <option value=\"Kg\"> Kilogramos</option>\n");
      out.write("                    <option value=\"g\"> Gramos</option>\n");
      out.write("                    <option value=\"pza\">Pieza</option>\n");
      out.write("                    <option value=\"lt\">Litros</option>\n");
      out.write("                    <option value=\"ml\">Mililitros</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"fechaCompra\" class=\"text-primary\">Fecha de compra</label>\n");
      out.write("                <input type=\"date\" class=\"form-control\" id=\"fechaCompra\" name=\"fechaCompra\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"fechaCaducidad\" class=\"text-primary\">Fecha de caducidad</label>\n");
      out.write("                <input type=\"date\" class=\"form-control\" id=\"fechaCaducidad\" name=\"fechaCaducidad\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"nombreProveedor\" class=\"text-primary\">Nombre del Proveedor</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"nombreProveedor\" placeholder=\"Ejemplo: Proveedor AAA\" name=\"nombreProveedor\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"descripcion\" class=\"text-primary\">Breve descripción del producto</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"descripcion\" name=\"descripcion\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"comentarios\" class=\"text-primary\">Comentarios adicionales</label>\n");
      out.write("                <textarea class=\"form-control\" id=\"comentarios\" rows=\"3\" name=\"comentarios\"></textarea>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 text-right\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary mt-3 mb-3\">Agregar al inventario</button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write(" \n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
